# Generated by Django 4.2.17 on 2026-09-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_reward_based_commissions'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='referralcommission',
            index=models.Index(fields=['user', 'status'], name='refcomm_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='referralcommission',
            index=models.Index(fields=['source_reward'], name='refcomm_source_reward_idx'),
        ),
        migrations.AddIndex(
            model_name='referralcommission',
            index=models.Index(fields=['cycle_date', 'status'], name='refcomm_cycle_status_idx'),
        ),
        migrations.AddIndex(
            model_name='referralcommission',
            index=models.Index(fields=['user', 'level'], name='refcomm_user_level_idx'),
        ),
        migrations.AddConstraint(
            model_name='referralcommission',
            constraint=models.CheckConstraint(check=models.Q(('commission_amount__gte', 0)), name='refcomm_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='referralcommission',
            constraint=models.CheckConstraint(check=models.Q(('commission_rate__gte', 0)), name='refcomm_rate_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='referralcommission',
            constraint=models.CheckConstraint(check=models.Q(('level__gte', 1)), name='refcomm_level_positive'),
        ),
    ]
