# Generated by Django 4.2.17 on 2026-09-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='event_key',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('VIP', 'VIP'), ('REWARD', 'Reward'), ('REFERRAL', 'Referral'), ('SUPPORT', 'Support'), ('SECURITY', 'Security'), ('ANNOUNCEMENT', 'Announcement'), ('SYSTEM', 'System')], db_index=True, max_length=16),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'notification_type', '-created_at'], name='notificatio_user_id_17cab8_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'event_key'], name='notificatio_user_id_4c17eb_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('event_key', ''), _negated=True), fields=('user', 'event_key'), name='uniq_notification_event_per_user'),
        ),
    ]
