# Generated by Django 4.2.17 on 2026-09-15 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valuation_date', models.DateField(db_index=True, unique=True)),
                ('value', models.DecimalField(decimal_places=8, max_digits=24)),
                ('currency', models.CharField(default='USDT', max_length=8)),
                ('is_demo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Company valuations',
                'ordering': ['valuation_date'],
            },
        ),
        migrations.CreateModel(
            name='HumanIDCounter',
            fields=[
                ('prefix', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('last_value', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Human ID counter',
                'verbose_name_plural': 'Human ID counters',
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField(blank=True)),
                ('value_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('boolean', 'Boolean'), ('json', 'JSON')], default='string', max_length=16)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('SUSPEND', 'Suspend'), ('ADJUST', 'Manual balance adjustment'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('OTHER', 'Other')], max_length=32)),
                ('target_type', models.CharField(blank=True, max_length=64)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor_user', '-created_at'], name='core_auditl_actor_u_8dc22f_idx'), models.Index(fields=['target_type', 'target_id'], name='core_auditl_target__6c66b3_idx')],
            },
        ),
    ]
