# Generated by Django 4.2.17 on 2026-09-15 19:25

import apps.core.db
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deposit_id', apps.core.db.HumanIDField(db_index=True, editable=False, max_length=19, padding=8, prefix='DEP', unique=True)),
                ('asset', models.CharField(default='USDT', max_length=10)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=24)),
                ('order_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('tx_hash', models.CharField(blank=True, db_index=True, max_length=128)),
                ('deposit_address', models.CharField(help_text='Address captured at submission time; survives later admin changes.', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=10)),
                ('admin_note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='wallet.network')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='deposits_de_user_id_2e2d07_idx'), models.Index(fields=['status', '-created_at'], name='deposits_de_status_c5f37f_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='deposit',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='deposit_amount_positive'),
        ),
    ]
