# Generated by Django 4.2.17 on 2026-09-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='verification_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='deposit',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
