# Generated by Django 4.2.17 on 2026-09-19 18:20

import apps.deposits.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deposits', '0002_deposit_verification_note_deposit_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposits_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deposit',
            name='screenshot',
            field=models.FileField(blank=True, max_length=255, upload_to=apps.deposits.models.deposit_screenshot_path),
        ),
        migrations.AddConstraint(
            model_name='deposit',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'APPROVED']), models.Q(('tx_hash', ''), _negated=True)), fields=('tx_hash',), name='deposit_unique_active_tx_hash'),
        ),
    ]
