"""Referral relationships and commissions (Section 9).

The ``Referral`` row is the relationship record (one referrer per user,
enforced by a OneToOne constraint). ``ReferralCommission`` is generated by
an eligible **VIP reward** (Section 8) — never by registration,
deposits, or withdrawals — and every commission snapshots the rate, level,
and source-reward amount at creation time so later configuration changes
never rewrite history.
"""

from django.conf import settings
from django.db import models

from apps.core.db import HumanIDField, TimeStampedModel, money_field


class Referral(models.Model):
    """Referral relationship between two users."""

    class Status(models.TextChoices):
        ACTIVE = 'ACTIVE', 'Active'
        INACTIVE = 'INACTIVE', 'Inactive'
        BLOCKED = 'BLOCKED', 'Blocked'

    referrer = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        related_name='referrals_made',
    )
    referred_user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        related_name='referral_received',
    )
    status = models.CharField(max_length=10, choices=Status.choices, default=Status.ACTIVE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        indexes = [
            models.Index(fields=['referrer', 'status'], name='referral_referrer_status_idx'),
        ]
        constraints = [
            models.CheckConstraint(
                check=~models.Q(referrer=models.F('referred_user')),
                name='referral_no_self_reference',
            ),
        ]

    def clean(self) -> None:
        if self.referrer_id == self.referred_user_id:
            raise ValueError('A user cannot refer themselves.')

    def __str__(self) -> str:
        return f'{self.referrer} -> {self.referred_user}'


class ReferralCommission(TimeStampedModel):
    """Commission earned by a referrer from an eligible downstream VIP reward.

    ``source_reward`` is OneToOne per (referrer, level): the (reward,
    beneficiary, level) uniqueness is enforced at the DATABASE level via the
    ``idempotency_key`` unique column, so Celery retries, duplicate reward
    processing, and racing workers can never pay a commission twice.
    ``commission_rate``, ``level``, and the source amounts are SNAPSHOTTED at
    creation — later rate changes never rewrite history (§48).
    """

    class Status(models.TextChoices):
        PENDING = 'PENDING', 'Pending'
        CREDITED = 'CREDITED', 'Credited'
        FAILED = 'FAILED', 'Failed'
        REVERSED = 'REVERSED', 'Reversed'

    commission_id = HumanIDField(prefix='COM', padding=8)
    # The beneficiary of the commission (the referrer at ``level``).
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        related_name='referral_commissions_earned',
    )
    # The user whose reward generated the commission.
    source_user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        related_name='referral_commissions_generated',
    )
    # The relationship row the commission was paid through.
    referral = models.ForeignKey(
        'Referral',
        on_delete=models.PROTECT,
        related_name='commissions',
    )
    level = models.PositiveSmallIntegerField(db_index=True)
    source_reward = models.ForeignKey(
        'vip.VIPReward',
        on_delete=models.PROTECT,
        related_name='referral_commissions',
    )
    # Snapshot of the reward credited amount at commission creation.
    source_reward_amount = money_field()
    commission_rate = models.DecimalField(max_digits=5, decimal_places=4)
    commission_amount = money_field()
    # Reward cycle the source reward belongs to (always set at creation;
    # nullable only so the reshape migration needs no default for old rows).
    cycle_date = models.DateField(null=True, blank=True, db_index=True)
    status = models.CharField(
        max_length=12,
        choices=Status.choices,
        default=Status.PENDING,
        db_index=True,
    )
    wallet_transaction = models.ForeignKey(
        'wallet.WalletTransaction',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='referral_commissions',
    )
    # Deterministic: REF_COMM_<reward_id>_<beneficiary_user_id>_<level>.
    idempotency_key = models.CharField(max_length=128, unique=True)
    # Short internal failure note; never rendered to users.
    error_info = models.CharField(max_length=255, blank=True, default='')
    processed_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['user', 'status'], name='refcomm_user_status_idx'),
            models.Index(fields=['source_reward'], name='refcomm_source_reward_idx'),
            models.Index(fields=['cycle_date', 'status'], name='refcomm_cycle_status_idx'),
            models.Index(fields=['user', 'level'], name='refcomm_user_level_idx'),
        ]
        constraints = [
            models.CheckConstraint(check=models.Q(commission_amount__gte=0), name='refcomm_amount_nonnegative'),
            models.CheckConstraint(check=models.Q(commission_rate__gte=0), name='refcomm_rate_nonnegative'),
            models.CheckConstraint(check=models.Q(level__gte=1), name='refcomm_level_positive'),
        ]

    def clean(self) -> None:
        if self.user_id == self.source_user_id:
            raise ValueError('Commission beneficiary and source user must differ.')

    def __str__(self) -> str:
        return f'{self.commission_id} ({self.status})'
