# Generated by Django 4.2.17 on 2026-09-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresettoken_loginactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kyc_status',
            field=models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PENDING', 'Verification pending'), ('APPROVED', 'Verified'), ('REJECTED', 'Verification failed')], db_index=True, default='UNVERIFIED', help_text='Set ONLY by a real identity-verification provider event.', max_length=12),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
