# Generated by Django 4.2.17 on 2026-09-15 19:25

import apps.core.db
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.CharField(default='USDT', max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('qr_code', models.CharField(blank=True, help_text='Path or URL reference to the QR image.', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['-is_active', 'network__sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('asset', models.CharField(default='USDT', max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_id', apps.core.db.HumanIDField(db_index=True, editable=False, max_length=19, padding=8, prefix='TXN', unique=True)),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('VIP_PURCHASE', 'VIP purchase'), ('VIP_REWARD', 'VIP reward'), ('REFERRAL_COMMISSION', 'Referral commission'), ('WELCOME_BONUS', 'Welcome bonus'), ('REFUND', 'Refund'), ('ADJUSTMENT', 'Adjustment')], db_index=True, max_length=24)),
                ('direction', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=6)),
                ('balance_type', models.CharField(choices=[('TOTAL', 'Total'), ('DEPOSIT', 'Deposit'), ('WITHDRAWABLE', 'Withdrawable'), ('BONUS', 'Bonus'), ('LOCKED', 'Locked'), ('PENDING', 'Pending')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=24)),
                ('reference_type', models.CharField(blank=True, max_length=64)),
                ('reference_id', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('REVERSED', 'Reversed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=12)),
                ('idempotency_key', models.CharField(blank=True, help_text='Optional unique key; a retried job/request with the same key cannot create a second ledger row.', max_length=128, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_balance', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('deposit_balance', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('withdrawable_balance', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('pending_balance', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('locked_balance', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('bonus_balance', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='network',
            constraint=models.UniqueConstraint(fields=('code', 'asset'), name='network_code_asset_unique'),
        ),
        migrations.AddField(
            model_name='depositaddress',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposit_addresses', to='wallet.network'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['user', '-created_at'], name='wallet_wall_user_id_801842_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['transaction_type', '-created_at'], name='wallet_wall_transac_f17c41_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['reference_type', 'reference_id'], name='wallet_wall_referen_a44abf_idx'),
        ),
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='ledger_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.CheckConstraint(check=models.Q(('direction__in', ['CREDIT', 'DEBIT'])), name='ledger_direction_valid'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(check=models.Q(('total_balance__gte', 0)), name='wallet_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(check=models.Q(('deposit_balance__gte', 0)), name='wallet_deposit_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(check=models.Q(('withdrawable_balance__gte', 0)), name='wallet_withdrawable_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(check=models.Q(('pending_balance__gte', 0)), name='wallet_pending_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(check=models.Q(('locked_balance__gte', 0)), name='wallet_locked_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(check=models.Q(('bonus_balance__gte', 0)), name='wallet_bonus_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='depositaddress',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('network', 'asset', 'address'), name='depositaddress_unique_active_per_network_asset'),
        ),
    ]
