# Generated by Django 4.2.17 on 2026-09-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='depositaddress',
            name='depositaddress_unique_active_per_network_asset',
        ),
        migrations.AddConstraint(
            model_name='depositaddress',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('network', 'asset'), name='depositaddress_unique_active_per_network_asset'),
        ),
    ]
