# Generated by Django 4.2.17 on 2026-09-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_remove_depositaddress_depositaddress_unique_active_per_network_asset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('VIP_PURCHASE', 'VIP purchase'), ('VIP_REWARD', 'VIP reward'), ('REFERRAL_COMMISSION', 'Referral commission'), ('WELCOME_BONUS', 'Welcome bonus'), ('REFUND', 'Refund'), ('ADJUSTMENT', 'Adjustment'), ('LOCK', 'Lock (withdrawable → locked)'), ('RELEASE', 'Release (locked → withdrawable)'), ('TRANSFER', 'Internal bucket transfer')], db_index=True, max_length=24),
        ),
    ]
