# Generated by Django 4.2.17 on 2026-09-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_wallettransaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='contract_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='network',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='network',
            name='min_deposit',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='network',
            name='min_withdrawal',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='network',
            name='network_warning',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='network',
            name='withdrawal_fee',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='network',
            name='withdrawal_fee_is_percent',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='network',
            constraint=models.CheckConstraint(check=models.Q(('min_deposit__isnull', True), ('min_deposit__gt', 0), _connector='OR'), name='network_min_deposit_positive'),
        ),
        migrations.AddConstraint(
            model_name='network',
            constraint=models.CheckConstraint(check=models.Q(('min_withdrawal__isnull', True), ('min_withdrawal__gt', 0), _connector='OR'), name='network_min_withdrawal_positive'),
        ),
        migrations.AddConstraint(
            model_name='network',
            constraint=models.CheckConstraint(check=models.Q(('withdrawal_fee__isnull', True), ('withdrawal_fee__gte', 0), _connector='OR'), name='network_withdrawal_fee_nonnegative'),
        ),
    ]
