# Generated by Django 4.2.17 on 2026-09-15 19:25

import apps.core.db
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vip', '0001_initial'),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maximum_amount', models.DecimalField(decimal_places=8, max_digits=24, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('required_vip_plan', models.ForeignKey(blank=True, help_text='Minimum VIP plan required for amounts up to maximum_amount.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_rules', to='vip.vipplan')),
            ],
            options={
                'ordering': ['maximum_amount'],
            },
        ),
        migrations.CreateModel(
            name='SimulatedWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_wallet', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=24)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='COMPLETED', max_length=10)),
                ('network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallet.network')),
            ],
            options={
                'verbose_name': 'Simulated withdrawal (demo)',
                'verbose_name_plural': 'Simulated withdrawals (demo)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('withdrawal_id', apps.core.db.HumanIDField(db_index=True, editable=False, max_length=19, padding=8, prefix='WDR', unique=True)),
                ('asset', models.CharField(default='USDT', max_length=10)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=24)),
                ('wallet_address', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=12)),
                ('tx_hash', models.CharField(blank=True, max_length=128)),
                ('admin_note', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='wallet.network')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='withdrawals_user_id_d1d349_idx'), models.Index(fields=['status', '-created_at'], name='withdrawals_status_fbe99c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='withdrawal',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='withdrawal_amount_positive'),
        ),
    ]
