# Generated by Django 4.2.17 on 2026-09-19 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawals', '0002_withdrawal_section10_reshape'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SimulatedWithdrawal',
        ),
    ]
