# Generated by Django 4.2.17 on 2026-09-19 18:20

import apps.withdrawals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawals', '0003_delete_simulatedwithdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='qr_image',
            field=models.FileField(blank=True, max_length=255, upload_to=apps.withdrawals.models.withdrawal_qr_path),
        ),
    ]
