# Generated by Django 4.2.17 on 2026-09-15 19:25

import apps.core.db
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VIPPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('plan_number', models.PositiveIntegerField(unique=True)),
                ('investment_amount', models.DecimalField(decimal_places=8, max_digits=24)),
                ('target_amount', models.DecimalField(decimal_places=8, max_digits=24)),
                ('daily_rate', models.DecimalField(decimal_places=4, help_text='Fraction of investment credited per day, e.g. 0.25 = 25%.', max_digits=5)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'plan_number'],
            },
        ),
        migrations.CreateModel(
            name='VIPPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_id', apps.core.db.HumanIDField(db_index=True, editable=False, max_length=19, padding=8, prefix='VIP', unique=True)),
                ('plan_name_snapshot', models.CharField(max_length=64)),
                ('investment_amount', models.DecimalField(decimal_places=8, max_digits=24)),
                ('target_amount', models.DecimalField(decimal_places=8, max_digits=24)),
                ('daily_rate_snapshot', models.DecimalField(decimal_places=4, max_digits=5)),
                ('amount_received', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=12)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vip_purchases', to=settings.AUTH_USER_MODEL)),
                ('vip_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='vip.vipplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VIPReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reward_id', apps.core.db.HumanIDField(db_index=True, editable=False, max_length=19, padding=8, prefix='REW', unique=True)),
                ('reward_date', models.DateField(db_index=True)),
                ('calculated_amount', models.DecimalField(decimal_places=8, max_digits=24)),
                ('credited_amount', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], db_index=True, default='PENDING', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vip_rewards', to=settings.AUTH_USER_MODEL)),
                ('vip_purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rewards', to='vip.vippurchase')),
                ('wallet_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vip_rewards', to='wallet.wallettransaction')),
            ],
            options={
                'ordering': ['-reward_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='vipplan',
            constraint=models.CheckConstraint(check=models.Q(('target_amount__gt', 0)), name='vipplan_target_positive'),
        ),
        migrations.AddConstraint(
            model_name='vipplan',
            constraint=models.CheckConstraint(check=models.Q(('daily_rate__gt', 0)), name='vipplan_rate_positive'),
        ),
        migrations.AddConstraint(
            model_name='vipreward',
            constraint=models.UniqueConstraint(fields=('vip_purchase', 'reward_date'), name='vipreward_unique_purchase_date'),
        ),
        migrations.AddIndex(
            model_name='vippurchase',
            index=models.Index(fields=['user', '-created_at'], name='vip_vippurc_user_id_05bdcc_idx'),
        ),
        migrations.AddIndex(
            model_name='vippurchase',
            index=models.Index(fields=['status', '-created_at'], name='vip_vippurc_status_65e06a_idx'),
        ),
    ]
