# Generated by Django 4.2.17 on 2026-09-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vippurchase',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AddConstraint(
            model_name='vippurchase',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__startswith', 'WELCOME_CLAIM_')), fields=('user',), name='vippurchase_one_welcome_claim_per_user'),
        ),
    ]
