# Generated by Django 4.2.17 on 2026-09-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip', '0003_reward_engine_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vipreward',
            options={'ordering': ['-reward_date', '-created_at']},
        ),
        migrations.AlterField(
            model_name='vippurchase',
            name='last_reward_cycle',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
